version: '3.12'

services:
  postgres-db:
    image: postgres:latest
    container_name: db_for_core
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  todo_core:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    environment:
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db_for_core
      DB_PORT: ${DB_PORT}
      PYTHONUNBUFFERED: 1
    entrypoint:
      - ./entrypoint.sh


volumes:
  pg_data:
