version: '3.12'
x-environment-defaults: &environment-defaults
  DEBUG: ${DEBUG}
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: "postgres-db"
  DB_PORT: ${DB_PORT}
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  SECRET_KEY: ${SECRET_KEY}
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092



services:
  postgres-db:
    image: postgres:latest
    container_name: db_for_core
    environment:
      <<: *environment-defaults
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    depends_on:
      - redis
      - postgres-db
    environment:
      <<: *environment-defaults

  celery-beat:
    build:
      context: .
    depends_on:
      - celery
      - redis
      - postgres-db
    environment:
      <<: *environment-defaults

  todo_core:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis
      - celery
      - celery-beat
    environment:
      <<: *environment-defaults
      PYTHONUNBUFFERED: 1
    entrypoint:
      - ./entrypoint.sh
    networks:
      - kafka-net


volumes:
  pg_data:

networks:
  kafka-net:
    external: true

