# Generated by Django 5.0.6 on 2024-07-08 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectModel",
            fields=[
                (
                    "project_pk",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("logo", models.URLField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectParticipantsModel",
            fields=[
                (
                    "participation_pk",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("participant_id", models.PositiveIntegerField()),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.projectmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "task_pk",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("reopened", "Reopened"),
                            ("closed", "Closed"),
                        ]
                    ),
                ),
                ("executor_id", models.PositiveIntegerField(null=True)),
                ("executor_name", models.CharField(max_length=255, null=True)),
                ("due_date", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.projectmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("title", "project")},
            },
        ),
        migrations.CreateModel(
            name="TasksAttachmentsModel",
            fields=[
                (
                    "attachment_pk",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("attachment", models.URLField()),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.taskmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskSubscribersModel",
            fields=[
                (
                    "subscription_pk",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("reopened", "Reopened"),
                            ("closed", "Closed"),
                        ]
                    ),
                ),
                ("subscriber_id", models.PositiveIntegerField()),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.taskmodel"
                    ),
                ),
            ],
        ),
    ]
