# Generated by Django 5.0.7 on 2024-07-24 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "project_pk",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("logo_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectParticipants",
            fields=[
                (
                    "project_participants_pk",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("participant_id", models.PositiveIntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_pk",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("reopened", "Reopened"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                    ),
                ),
                ("executor_id", models.PositiveIntegerField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.project"
                    ),
                ),
            ],
            options={
                "unique_together": {("title", "project")},
            },
        ),
        migrations.CreateModel(
            name="TasksAttachments",
            fields=[
                (
                    "task_attachments_pk",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("attachment_id", models.PositiveIntegerField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.task"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskSubscribers",
            fields=[
                (
                    "task_subscribers_pk",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("subscriber_id", models.PositiveIntegerField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.task"
                    ),
                ),
            ],
        ),
    ]
