# Generated by Django 5.0.6 on 2024-07-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmodel",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="taskmodel",
            old_name="project",
            new_name="project_id",
        ),
        migrations.RemoveField(
            model_name="projectmodel",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="tasksattachmentsmodel",
            name="attachment",
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="logo_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasksattachmentsmodel",
            name="attachment_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="taskmodel",
            unique_together={("title", "project_id")},
        ),
    ]
