# Generated by Django 5.0.7 on 2024-07-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_projectmodel_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectModel",
            new_name="Project",
        ),
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.RenameModel(
            old_name="ProjectParticipantsModel",
            new_name="ProjectParticipant",
        ),
        migrations.RenameModel(
            old_name="TaskModel",
            new_name="Task",
        ),
        migrations.RenameModel(
            old_name="TasksAttachmentsModel",
            new_name="TasksAttachment",
        ),
        migrations.RenameModel(
            old_name="TaskSubscribersModel",
            new_name="TaskSubscriber",
        ),
    ]
