# Generated by Django 5.0.7 on 2024-07-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_taskmodel_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectparticipant",
            old_name="participation_pk",
            new_name="project_participant_pk",
        ),
        migrations.RenameField(
            model_name="tasksattachment",
            old_name="attachment_pk",
            new_name="task_attachment_pk",
        ),
        migrations.RenameField(
            model_name="tasksubscriber",
            old_name="subscription_pk",
            new_name="task_subscriber_pk",
        ),
        migrations.RemoveField(
            model_name="task",
            name="executor_name",
        ),
        migrations.RemoveField(
            model_name="tasksubscriber",
            name="task_status",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("reopened", "Reopened"),
                    ("closed", "Closed"),
                ],
                default="open",
            ),
        ),
    ]
