# Generated by Django 5.0.7 on 2024-07-31 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0004_rename_participation_pk_projectparticipant_project_participant_pk_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskNotification",
            fields=[
                (
                    "task_notification_pk",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("notified_user_id", models.PositiveIntegerField()),
                ("notification_date", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("update status", "update_status"),
                            ("deadline", "deadline"),
                        ]
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.task"
                    ),
                ),
            ],
        ),
    ]
