# Generated by Django 5.0.7 on 2024-10-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_tasknotification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="logo_id",
        ),
        migrations.AddField(
            model_name="project",
            name="creator_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="creator_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tasknotification",
            name="notification_type",
            field=models.CharField(
                choices=[("update status", "update status"), ("deadline", "deadline")]
            ),
        ),
        migrations.DeleteModel(
            name="TasksAttachment",
        ),
    ]
