name: Run tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        -  5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install Dependencies
      run: poetry install

    - name: Run migrations
      run: |
        cd core
        poetry run python manage.py migrate --settings=core.settings.ci_cd

    - name: Start Celery worker
      run: |
        cd core
        poetry run celery -A core worker --loglevel=info &

    - name: Start Celery beat
      run: |
        cd core
        poetry run celery -A core beat --loglevel=info &

    - name: Run Tests
      env:
        DEBUG: ${{ secrets.DEBUG }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_HOST: ${{ secrets.POSTGRES_HOST }}
        DB_NAME: ${{ secrets.POSTGRES_DB }}
        DB_USER: ${{ secrets.POSTGRES_USER }}
        DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
        cd core
        poetry run python manage.py test --settings=core.settings.ci_cd
