name: Run tests

on:
  push:
    branches: [ "develop", "fix-github-actions" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
          POSTGRES_HOST: postgres
        ports:
        -  5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install Dependencies
      run: poetry install

    - name: Setup database
      run: psql -h postgres -U postgres -c 'CREATE DATABASE "postgres";'
      env:
        POSTGRES_PASSWORD: postgres

    - name: Run Tests
      run: |
        cd core
        poetry run python manage.py test
      env:
        DBURL: postgres://postgres:postgres@localhost:5432/postgres
